### ISSUE TITLE
QoS SLA

### ISSUE THREAD

**Issue by marcvs** [indigo-dc/slam#3]
Hi Guys,

this is not an issue, but I'm wondering if you have included the QoS in Storage into your SLA schemes. The thing is that we'd like to use SLAM from WP4/CDMI-QoS to determine whether users are allowed to stage files from tape to disk or to ssd and also to limit how often this may be done.

Anyhow: Where are you working and in which team?
I'm Marcus from KIT

**Comment by toszep** [comment]
We are working  on Storage SLA right now, so we try include your requirements. We'll discus this off-line.
Tomasz from Cyfronet ;-)
